Revert of add ConvertYUVAToARGBRow_MMX to media_perftests (patchset #2 id:20001 of https://codereview.chromium.org/1414023003/ )
Reason for revert:
Compile error on Win Bots:
FAILED: ninja -t msvc -e environment.x64 -- E:\b\build\goma/gomacc.exe "E:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64/cl.exe" /nologo /showIncludes /FC @obj/media/base/perftests/yuv_convert_perftest.obj.rsp /c ../../media/base/yuv_convert_perftest.cc /Foobj/media/base/perftests/yuv_convert_perftest.obj /Fdobj/media/base/perftests_cc.pdb
e:\b\build\slave\win_x64_gn\build\src\third_party\libyuv\include\libyuv\row.h(16) : fatalerror C1083: Cannot open include file: 'libyuv/basic_types.h': No such file or directory

Original issue's description:
> add ConvertYUVAToARGBRow_MMX to media_perftests
>
> Add YUVConvertPerfTest.ConvertYUVAToARGBRow_MMX and YUVConvertPerfTest.I422ToARGBRow_SSSE3 to media_perftests.
> Fix math error when printing results by clearing the MMX state before doing float math.
>
> BUG=libyuv:473
>
> Committed: https://crrev.com/c6ab707df6a54b2acffb7115574a794b7a748ea9
> Cr-Commit-Position: refs/heads/master@{#357716}

TBR=xhwang@chromium.org,fbarchard@chromium.org,fbarchard@google.com
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=libyuv:473

Review URL: https://codereview.chromium.org/1403413005

Cr-Original-Commit-Position: refs/heads/master@{#357802}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 7a019e39556b833549f2b849392f13613343937c