Disable VideoCaptureDeviceTest.CaptureMjpeg on Win10.
When a webcam is available (at least with Logitech C920) it
fails like this:
[ RUN      ] VideoCaptureDeviceTest.CaptureMjpeg
e:\b\build\slave\win_builder\build\src\media\capture\video\video_capture_device_unittest.cc(457): error: Value of: PIXEL_FORMAT_MJPEG
  Actual: 14
Expected: last_format().pixel_format
Which is: 1
e:\b\build\slave\win_builder\build\src\media\capture\video\video_capture_device_unittest.cc(459): error: Expected: (static_cast<size_t>(1280 * 720)) >= (last_format().ImageAllocationSize()), actual: 921600 vs 1382400
[  FAILED  ] VideoCaptureDeviceTest.CaptureMjpeg (707 ms)

BUG=570604

Review URL: https://codereview.chromium.org/1536593003

Cr-Original-Commit-Position: refs/heads/master@{#365793}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 320988844613f7e79b423e76ad2d4acfe2c45437