Revert of [Cast] Compute utilization metrics and add performance overlay. (patchset #2 id:40001 of https://codereview.chromium.org/1148233002/)
Reason for revert:
Reverting due to compile failure on Google Chrome Mac builder:
../../media/cast/sender/h264_vt_encoder_unittest.cc:282:38: error: no viable conversion from 'Callback<typename internal::BindState<typename internal::FunctorTraits<void (MetadataRecorder::*)(scoped_ptr<EncodedFrame, DefaultDeleter<EncodedFrame> >)>::RunnableType, typename internal::FunctorTraits<void (MetadataRecorder::*)(scoped_ptr<EncodedFrame, DefaultDeleter<EncodedFrame> >)>::RunType, internal::TypeList<typename internal::CallbackParamTraits<MetadataRecorder *>::StorageType> >::UnboundRunType>' to 'Callback<void (scoped_ptr<media::cast::SenderEncodedFrame>)>'
  VideoEncoder::FrameEncodedCallback cb = base::Bind(
                                     ^    ~~~~~~~~~~~
../../base/callback.h:358:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'base::Callback<typename internal::BindState<typename internal::FunctorTraits<void (MetadataRecorder::*)(scoped_ptr<EncodedFrame, DefaultDeleter<EncodedFrame> >)>::RunnableType, typename internal::FunctorTraits<void (MetadataRecorder::*)(scoped_ptr<EncodedFrame, DefaultDeleter<EncodedFrame> >)>::RunType, internal::TypeList<typename internal::CallbackParamTraits<MetadataRecorder *>::StorageType> >::UnboundRunType>' to 'base::Callback<void (scoped_ptr<media::cast::SenderEncodedFrame, base::DefaultDeleter<media::cast::SenderEncodedFrame> >)> &&' for 1st argument
class Callback;

http://build.chromium.org/p/chromium.chrome/buildstatus?builder=Google%20Chrome%20Mac&number=1293

Original issue's description:
> [Cast] Compute utilization metrics and add performance overlay.
>
> Adds computation of two frame-level utilization metrics to the software
> VP8 encoder in Cast: deadline utilization and lossy utilization.  The
> first is a measure of how long the encoding of each frame takes compared
> to the frame duration.  The second is a measure of the complexity of a
> frame, in terms of the quality versus encoded size trade-off.
>
> In a future change, these utilization metrics will be sent as feedback
> signals to the producer of the video frames, allowing the producer to
> adjust data volumes based on the consumer's capability throughout a
> session.  See bug for more details.
>
> Also, this change adds an overlay display, where frame-level performance
> metrics are rendered in the lower-right corner of each video frame just
> before it is sent.  This provides an "on screen display" of end-to-end
> system performance.  This is turned on with a command line argument:
> --vmodule=performance_metrics_overlay=3
>
> BUG=156767
>
> Committed: https://crrev.com/d9e741512cd6ea56cefd0173b371d0dd29f0cce5
> Cr-Commit-Position: refs/heads/master@{#330896}

TBR=hubbe@chromium.org,miu@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=156767

Review URL: https://codereview.chromium.org/1143363005

Cr-Original-Commit-Position: refs/heads/master@{#330906}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: dcd1d5968e79c93d9fe9ca1a523d6f83b94a6ae6