Revert of [Mojo Video Capture] Hook up video capture service behind a feature flag (patchset #9 id:180001 of https://codereview.chromium.org/2867213004/ )
Reason for revert:
This CL appears to cause test failures on the Webkit Android bots for blink_heap_unittests and webkit_unit_tests.

Example failing build:
https://luci-milo.appspot.com/buildbot/chromium.webkit/WebKit%20Android%20%28Nexus4%29/65022

OSError: [Errno 2] No such file or directory: '/b/c/b/WebKit_Android__Nexus4_/src/out/Release/gen/services/video_capture/manifest.json'

Original issue's description:
> [Mojo Video Capture] Hook up video capture service behind a feature flag
>
> This CL is part of the Mojo Video Capture work. For the bigger picture,
> see [1] CL25.
>
> After this CL, the video capture service can be enabled by starting Chrome with
> command-line flag --enable-features=MojoVideoCapture.
>
> Changes in this CL:
> * Add a base::Feature kMojoVideoCapture to allow switching the service on and
>   off.
> * Add a class VideoCaptureProviderSwitcher that can route device capture
>   requests to the service's VideoCaptureProvider while routing screen capture
>   requests to the InProcessVideoCaptureProvider.
> * Hook up the VideoCaptureProviderSwitcher in the factory code in
>   MediaStreamManager.
> * Register video capture service in the service manager context for the Browser
>   process.
> * Remove build flag "enable_mojo_video_capture", since we want the service to
>   be testable in all builds.
> * Forward switches for using fake video capture devices to utility processes.
> * Add test cases for exercising the service to VideoCaptureBrowserTest.
>
> BUG=584797
> TEST=
>   content_browsertests --gtest_filter="VideoCaptureBrowserTest.*"
>
> [1] https://docs.google.com/a/chromium.org/document/d/1Qw7rw1AJy0QHXjha36jZNiEuxsxWslJ_X-zpOhijvI8/edit?usp=sharing
>
> Review-Url: https://codereview.chromium.org/2867213004
> Cr-Commit-Position: refs/heads/master@{#473358}
> Committed: https://chromium.googlesource.com/chromium/src/+/d99842d2bfbffba9b80aaa81aced1f1e7ebb39c8

TBR=rockot@chromium.org,emircan@chromium.org,mcasas@chromium.org,miu@chromium.org,piman@chromium.org,tsepez@chromium.org,chfremer@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=584797

Review-Url: https://codereview.chromium.org/2900583002
Cr-Original-Commit-Position: refs/heads/master@{#473495}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 0749fd4d1bf03b14b8d38cd5ccb2b32d0dac0836