Remove unnecessary check in IsSystemRealTimeMessage.
The 'data <= 0xff' check in IsSystemRealTimeMessage is unnecessary as
|data| is a uint8 integer. This CL removes the check to prevent the
following compilation error when building with '-Werror=type-limits'.

../../media/midi/midi_message_queue.cc: In function 'bool
media::{anonymous}::IsSystemRealTimeMessage(uint8)':
../../media/midi/midi_message_queue.cc:27:34: error: comparison is
always true due to limited range of data type [-Werror=type-limits]
   return 0xf8 <= data && data <= 0xff;
                                  ^

BUG=424334,427726
TEST=Build successfully with '-Werror=type-limits' using the GN flow.

Review URL: https://codereview.chromium.org/683693003

Cr-Original-Commit-Position: refs/heads/master@{#301803}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 4454938c07fd3d03112d0faae956f2fe47fc58be